// <auto-generated />
using System;
using ControleMaquinasMx.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleMaquinasMx_Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231213163553_AddPermissao")]
    partial class AddPermissao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ControleMaquinasMx_Domain.Models.Pacote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInstalacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaquinasId")
                        .HasColumnType("int");

                    b.Property<string>("NomeKb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaquinasId");

                    b.ToTable("Pacotes");
                });

            modelBuilder.Entity("ControleMaquinasMx_Domain.Models.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissoes");
                });

            modelBuilder.Entity("ControleMaquinasMx_Domain.Models.Usuario", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Login");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ControleMaquinasMx.Core.Models.Maquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Criticidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inventario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ondeso")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Maquinas");
                });

            modelBuilder.Entity("PermissaoUsuario", b =>
                {
                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuariosLogin")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PermissaoId", "UsuariosLogin");

                    b.HasIndex("UsuariosLogin");

                    b.ToTable("PermissaoUsuario");
                });

            modelBuilder.Entity("ControleMaquinasMx_Domain.Models.Pacote", b =>
                {
                    b.HasOne("ControleMaquinasMx.Core.Models.Maquina", "Maquinas")
                        .WithMany("Pacotes")
                        .HasForeignKey("MaquinasId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Maquinas");
                });

            modelBuilder.Entity("PermissaoUsuario", b =>
                {
                    b.HasOne("ControleMaquinasMx_Domain.Models.Permissao", null)
                        .WithMany()
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControleMaquinasMx_Domain.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosLogin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ControleMaquinasMx.Core.Models.Maquina", b =>
                {
                    b.Navigation("Pacotes");
                });
#pragma warning restore 612, 618
        }
    }
}
